#!/bin/bash

NAME=clogrid
VERSION=0.1.0-SNAPSHOT
JAR_INSTALL_DIR=/var/local/clogrid
ARTIFACT_UBERJAR_PATH=/home/lklich/Dokumenty/Projekty/LibertyGlobal/clogrid/init-script/clogrid-0.1.0-SNAPSHOT-standalone.jar
INIT_SCRIPT_INSTALL_DIR=/etc/init.d
ARTIFACT_INIT_SCRIPT_PATH=/home/lklich/Dokumenty/Projekty/LibertyGlobal/clogrid/init-script/clogridd
INSTALLED_INIT_SCRIPT_PATH=/etc/init.d/clogridd

#standalone jar
mkdir -p $JAR_INSTALL_DIR
cp $ARTIFACT_UBERJAR_PATH $JAR_INSTALL_DIR/"$NAME"-"$VERSION"-standalone.jar

#init script
mkdir -p $INIT_SCRIPT_INSTALL_DIR
cp $ARTIFACT_INIT_SCRIPT_PATH $INIT_SCRIPT_INSTALL_DIR
chmod u+x $INSTALLED_INIT_SCRIPT_PATH
